name: Chess Game

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  play-chess:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      # ðŸŸ¢ THIS IS THE WORKING BACKUP ROBOT
      - name: Run Chess Game
        uses: guilhermeprocopio/chess-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction_token: ${{ secrets.GITHUB_TOKEN }}
